<html>
<head>
<title>Python Examples to Make Algorithms more Robust with Exception Handling</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python示例通过异常处理使算法更加健壮</h1>
<blockquote>原文：<a href="https://pub.towardsai.net/python-examples-to-make-algorithm-more-robust-with-exception-handling-6bff7a127786?source=collection_archive---------0-----------------------#2021-09-12">https://pub.towardsai.net/python-examples-to-make-algorithm-more-robust-with-exception-handling-6bff7a127786?source=collection_archive---------0-----------------------#2021-09-12</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><h2 id="d817" class="ir is it bd b dl iu iv iw ix iy iz dk ja translated" aria-label="kicker paragraph"><a class="ae ep" href="https://towardsai.net/p/category/programming" rel="noopener ugc nofollow" target="_blank">编程</a></h2><div class=""/><div class=""><h2 id="2223" class="pw-subtitle-paragraph jz jc it bd b ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq dk translated">程序正常流程中的错误中断</h2></div><figure class="ks kt ku kv gt kw gh gi paragraph-image"><div role="button" tabindex="0" class="kx ky di kz bf la"><div class="gh gi kr"><img src="../Images/28e705647fa019947666245a2c08f37d.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*p5pwxmuY8bIBxmlf"/></div></div><figcaption class="ld le gj gh gi lf lg bd b be z dk translated">由<a class="ae lh" href="https://unsplash.com/@markusspiske?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">马库斯·斯皮斯克</a>在<a class="ae lh" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</figcaption></figure><blockquote class="li lj lk"><p id="d1ce" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">异常处理</em> </strong></p></blockquote><p id="a12f" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">例外的概念很简单。只有当程序的正常流程被错误中断时，才会发生异常。如果程序不能处理特定的操作，它会引发一个异常。异常只是一个表示错误的python对象。一旦python脚本引发异常，就必须立即处理。否则，程序将被终止。</p><blockquote class="li lj lk"><p id="e7de" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">试除Python中的</em> </strong></p></blockquote><p id="696f" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">在python中，try-except语句首先在try语句下运行程序。如果程序没有成功执行，它会在检测到错误的地方停止，并运行“except”块。这条语句帮助我们测试一段代码中的错误。</p><p id="f596" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">语法:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="f174" class="mq mr it mm b gy ms mt l mu mv">try:<br/>    Try statements</span><span id="78dd" class="mq mr it mm b gy mw mt l mu mv">except Exception_name:<br/>    Exception statements</span></pre><p id="9698" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">程序:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="4adc" class="mq mr it mm b gy ms mt l mu mv">a = 2<br/>b = 5</span><span id="a31c" class="mq mr it mm b gy mw mt l mu mv">try:<br/>    print(“Program is running…”)<br/>    print(a/b)<br/>    print(“program has worked”)<br/>    i = int(input(“Enter input : “))</span><span id="d56e" class="mq mr it mm b gy mw mt l mu mv">except ZeroDivisionError:<br/>    print(“Error: Division by zero is not possible”)</span><span id="4739" class="mq mr it mm b gy mw mt l mu mv">except Exception:<br/>    print(“Invalid Input”)</span><span id="f495" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">Output:<br/>// when b=5</strong></span><span id="80aa" class="mq mr it mm b gy mw mt l mu mv">Program is running…<br/>0.4<br/>program has worked<br/>Enter input : p<br/>Invalid Input</span><span id="48e8" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">//when b=0</strong></span><span id="d76a" class="mq mr it mm b gy mw mt l mu mv">Program is running…<br/>Error: Division by zero is not possible</span></pre><h2 id="86a7" class="mq mr it bd mx my mz dn na nb nc dp nd mi ne nf ng mj nh ni nj mk nk nl nm iz bi translated"><strong class="ak">说明:</strong></h2><p id="3441" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">从上面的程序中，让我们考虑两种情况:</p><ul class=""><li id="21eb" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh nx ny nz oa bi translated"><strong class="lo jd">当变量b = 5时</strong></li></ul><p id="4353" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">在这里，程序成功地执行了前3条try语句。第四个语句是输入一个输入(由用户输入)。让我们看看，如果在应该输入整数的地方输入一个字符，会发生什么情况。</p><p id="08c1" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">程序会将此视为错误，并执行“except”块“Exception”因此，将输出返回为“无效输入”</p><ul class=""><li id="6192" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh nx ny nz oa bi translated"><strong class="lo jd">当变量b = 0时</strong></li></ul><p id="45c6" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">在这里，程序成功地执行了第一个try语句。我们知道一个数不能被零整除；因此，这是一个错误，并直接跳转到异常块“ZeroDivisionError”。这就是我们如何接收到“错误:不能被零除”的输出</p><blockquote class="li lj lk"><p id="5cf0" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">清理行动</em> </strong></p></blockquote><p id="3dfc" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">如果程序成功执行或抛出异常，清理操作总是运行任务。为了执行清理操作，我们使用try语句的可选子句—最后，它将在任何条件下运行该语句下的任务。</p><p id="c573" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">程序:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="2709" class="mq mr it mm b gy ms mt l mu mv">a = 2<br/>b = 0</span><span id="159c" class="mq mr it mm b gy mw mt l mu mv">try:<br/>    print(“Program is running…”)<br/>    print(a/b)<br/>    print(“program has worked”)<br/>    i = int(input(“Enter input : “))</span><span id="de10" class="mq mr it mm b gy mw mt l mu mv">except ZeroDivisionError:<br/>    print("Error: Not possible, Division by zero")</span><span id="63cf" class="mq mr it mm b gy mw mt l mu mv">except Exception:<br/>    print(“Invalid Input”)</span><span id="cfc1" class="mq mr it mm b gy mw mt l mu mv">finally:<br/>    print(“Program has successfully ended….”)</span><span id="e21f" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">Output:<br/></strong>Program is running…<br/>Error: Not possible, Division by zero<br/>Program has successfully ended….</span></pre><h2 id="f668" class="mq mr it bd mx my mz dn na nb nc dp nd mi ne nf ng mj nh ni nj mk nk nl nm iz bi translated"><strong class="ak">说明:</strong></h2><p id="0368" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">在上面的程序中，您可以看到即使遇到异常,' finally '语句也会成功执行。但是它不会打印try块中剩余的语句。</p><div class="ob oc gp gr od oe"><a href="https://medium.com/pythoneers/forget-html-and-flask-start-using-streamlit-1b394cfe4595" rel="noopener follow" target="_blank"><div class="of ab fo"><div class="og ab oh cl cj oi"><h2 class="bd jd gy z fp oj fr fs ok fu fw jc bi translated">忘记HTML和Flask，开始使用Streamlit</h2><div class="ol l"><h3 class="bd b gy z fp oj fr fs ok fu fw dk translated">数据科学和机器学习的WebApp框架</h3></div><div class="om l"><p class="bd b dl z fp oj fr fs ok fu fw dk translated">medium.com</p></div></div><div class="on l"><div class="oo l op oq or on os lb oe"/></div></div></a></div><div class="ob oc gp gr od oe"><a rel="noopener  ugc nofollow" target="_blank" href="/latest-programming-languages-for-ai-5252d39e1c51"><div class="of ab fo"><div class="og ab oh cl cj oi"><h2 class="bd jd gy z fp oj fr fs ok fu fw jc bi translated">最新的人工智能编程语言</h2><div class="ol l"><h3 class="bd b gy z fp oj fr fs ok fu fw dk translated">人工智能未来娱乐它的语言</h3></div><div class="om l"><p class="bd b dl z fp oj fr fs ok fu fw dk translated">pub.towardsai.ne</p></div></div><div class="on l"><div class="ot l op oq or on os lb oe"/></div></div></a></div><blockquote class="li lj lk"><p id="476a" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">内置异常</em> </strong></p></blockquote><p id="1bb7" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">python程序中出现的所有异常都是类。此外，这些异常中的每一个都直接或间接地继承自exception类。</p><p id="a4fe" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">例如:让我们看看下面的图表。这里你可以看到“算术错误”异常继承了它的父类“异常”类。现在让我们更进一步，看看“溢出误差”此异常类直接继承自“算术错误”异常类，但间接继承自“异常”类。</p><p id="1bae" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">示意图:</strong></p><figure class="ks kt ku kv gt kw gh gi paragraph-image"><div class="gh gi ou"><img src="../Images/ec5a626f2905e6a61952509c2f9e354f.png" data-original-src="https://miro.medium.com/v2/resize:fit:1004/format:webp/1*42Hn8jM4sYFzr_bx_7TOAw.png"/></div><figcaption class="ld le gj gh gi lf lg bd b be z dk translated">图像<a class="ae lh" href="https://w3.cs.jmu.edu/lam2mo/cs240_2014_08/lab05-exceptions.html" rel="noopener ugc nofollow" target="_blank">来源</a></figcaption></figure><p id="5f66" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">一些内置的例外:</p><ul class=""><li id="7cb2" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh nx ny nz oa bi translated"><strong class="lo jd"> ZeroDivisionError </strong>:当模运算的除数或除数为零时，会出现这种错误。</li><li id="c89d" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh nx ny nz oa bi translated"><strong class="lo jd">缩进错误</strong>:当程序中有不正确的缩进时，会出现这种错误。</li><li id="069f" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh nx ny nz oa bi translated"><strong class="lo jd">内存错误</strong>:当一个特定的函数内存不足时，就会出现这种错误。</li><li id="1cbe" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh nx ny nz oa bi translated"><strong class="lo jd">类型错误</strong>:当一个程序的一个函数或操作被应用到一个具有不正确类型的对象时，出现类型错误。</li><li id="07ce" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh nx ny nz oa bi translated"><strong class="lo jd">语法错误</strong>:当解析器遇到语法错误时，会出现这种错误。</li></ul><p id="f2cc" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">程序:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="f7a8" class="mq mr it mm b gy ms mt l mu mv">a = 2<br/>b = 0</span><span id="7eb8" class="mq mr it mm b gy mw mt l mu mv">try:<br/>    print(“Program is running…”)<br/>    print(a/b)<br/>    print(“program has worked”)<br/>    except ZeroDivisionError as e:<br/>    print(“Error: Division by zero is not “)</span><span id="5efa" class="mq mr it mm b gy mw mt l mu mv">except SyntaxError as e:<br/>    print(“Error : Check your syntax”)</span><span id="1c5c" class="mq mr it mm b gy mw mt l mu mv">except NameError as e:<br/>    print(“Error : Variable not found”)</span><span id="b23b" class="mq mr it mm b gy mw mt l mu mv">finally:<br/>    print(“Program has successfully ended….”)</span><span id="39ee" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">Output:<br/>// when b = 0</strong></span><span id="4ed6" class="mq mr it mm b gy mw mt l mu mv">Program is running…<br/>Error: Division by zero is not<br/>Program has successfully ended….</span><span id="b877" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">// when a/b = a/c</strong></span><span id="47e3" class="mq mr it mm b gy mw mt l mu mv">Program is running…<br/>Error : Variable not found<br/>Program has successfully ended….</span></pre><h2 id="7279" class="mq mr it bd mx my mz dn na nb nc dp nd mi ne nf ng mj nh ni nj mk nk nl nm iz bi translated"><strong class="ak">解释:</strong></h2><p id="323e" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">从上面的程序中，让我们考虑两种情况:</p><ul class=""><li id="ebbc" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh nx ny nz oa bi translated"><strong class="lo jd">当b = 0时</strong></li></ul><p id="0c47" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">类似于前面的例子，我们知道一个数不能被零除。因此，程序在try语句的第二行停止，并跳转到“except”块。即ZeroDivisionError异常。</p><ul class=""><li id="1e32" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh nx ny nz oa bi translated"><strong class="lo jd">当a/b = a/c时</strong></li></ul><p id="7781" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">当我们将try语句的第二行从a/b → a/c改变时，程序识别出一个错误，因为变量‘c’是无效的。因此，解析器跳转到“NameError”异常。</p><blockquote class="li lj lk"><p id="1fdb" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">用户自定义异常</em> </strong></p></blockquote><p id="ca15" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">程序员可以通过创建新的异常类来创建他们的异常。这个概念被称为用户定义的异常。</p><p id="1727" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">程序:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="9200" class="mq mr it mm b gy ms mt l mu mv">class GuessError(Exception):<br/>    def __init__(self, message):<br/>        self.message = message</span><span id="606a" class="mq mr it mm b gy mw mt l mu mv">a = int(input(“Enter the input : “))</span><span id="7231" class="mq mr it mm b gy mw mt l mu mv">try:<br/>    if a &lt; 3:<br/>        raise GuessError(“Your guess is wrong. Number is less.”)</span><span id="9271" class="mq mr it mm b gy mw mt l mu mv">    elif a &gt; 3:<br/>        raise GuessError(“Your guess is wrong. Number is high.”)</span><span id="ebff" class="mq mr it mm b gy mw mt l mu mv">    else:<br/>        print(“Your guess is right. The value is : {}.”.format(a))</span><span id="ecfd" class="mq mr it mm b gy mw mt l mu mv">except GuessError as e:<br/>    print(e.message)</span><span id="4fc2" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">Output:</strong></span><span id="b938" class="mq mr it mm b gy mw mt l mu mv">Enter the input : 3<br/>Your guess is right. The value is : 3</span><span id="a150" class="mq mr it mm b gy mw mt l mu mv">Enter the input : 2<br/>Your guess is wrong. Number is less.</span><span id="3254" class="mq mr it mm b gy mw mt l mu mv">Enter the input : 5<br/>Your guess is wrong. Number is high.</span></pre><h2 id="57ed" class="mq mr it bd mx my mz dn na nb nc dp nd mi ne nf ng mj nh ni nj mk nk nl nm iz bi translated"><strong class="ak">解释:</strong></h2><p id="33de" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">您可以在上面的程序中看到，用户定义的异常“GuessError”是通过定义一个从基类“exception”继承的类来创建的创建一个构造函数来初始化该类的一个对象，以传递我们选择的错误消息。然后是通常的try-except语句，这些语句将按照程序应该执行的方式执行。</p><blockquote class="li lj lk"><p id="2230" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it"> Nzec错误</em> </strong></p></blockquote><p id="84b6" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">NZEC错误，也称为非零退出代码，是运行时发生的错误类型。当您的代码未能返回0时，会出现此错误。你的程序只有在返回0时才能成功执行。否则程序将根据错误类型返回一个非0的数字。</p><p id="6c2c" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">可能出现NZEC错误:</strong></p><ol class=""><li id="af6f" class="ns nt it lo b lp lq ls lt mi nu mj nv mk nw mh pa ny nz oa bi translated">当访问负数组索引时。</li><li id="0b86" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh pa ny nz oa bi translated">如果程序使用的内存超过了为运行程序分配的内存量。</li><li id="2efc" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh pa ny nz oa bi translated">因为基本的编程错误，比如把一个数除以零。</li><li id="c03b" class="ns nt it lo b lp ov ls ow mi ox mj oy mk oz mh pa ny nz oa bi translated">如果你想计算20以上的阶乘。</li></ol><p id="e662" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">例如</strong>，上面代码片段的NZEC错误可以使用try-except块语句解决。</p><p id="d280" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated"><strong class="lo jd">程序:</strong></p><pre class="ks kt ku kv gt ml mm mn mo aw mp bi"><span id="0c3d" class="mq mr it mm b gy ms mt l mu mv">for nzec in range(int(input())):<br/>    a=int(int())<br/>    b=list(map(int,input().split()))<br/>    c=0<br/>    ls=Null</span><span id="4aa7" class="mq mr it mm b gy mw mt l mu mv">    for i in b:<br/>        if n==Null or n&gt;i:<br/>            n=i<br/>            c=c+1</span><span id="8859" class="mq mr it mm b gy mw mt l mu mv">    print(c)</span><span id="f7e2" class="mq mr it mm b gy mw mt l mu mv"><strong class="mm jd">Solution:</strong></span><span id="45e7" class="mq mr it mm b gy mw mt l mu mv">try:<br/>    for nzec in range(int(input())):<br/>        a=int(int())<br/>        b=list(map(int,input().split()))<br/>        c=0<br/>        ls=Null</span><span id="14b9" class="mq mr it mm b gy mw mt l mu mv">        for i in b:<br/>            if n==Null or n&gt;i:<br/>                n=i<br/>                c=c+1</span><span id="24c7" class="mq mr it mm b gy mw mt l mu mv">        print(c)</span><span id="db67" class="mq mr it mm b gy mw mt l mu mv">except: pass</span></pre><h2 id="f927" class="mq mr it bd mx my mz dn na nb nc dp nd mi ne nf ng mj nh ni nj mk nk nl nm iz bi translated"><strong class="ak">解释:</strong></h2><p id="edb1" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">在上面的程序中，try-except语句可以解决NZEC错误，因为程序未能返回0(以结束程序)。这不是编程错误；相反，这是一个算法错误。因此，我们使用try-except语句来停止程序而不出错。</p><blockquote class="li lj lk"><p id="e10f" class="ll lm ln lo b lp lq kd lr ls lt kg lu lv lw lx ly lz ma mb mc md me mf mg mh im bi translated"><strong class="lo jd"> <em class="it">结论</em> </strong></p></blockquote><p id="98f2" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">总之，本文涵盖了异常处理的一些关键概念。我强烈建议阅读更多的文章，并使用python程序应用这些概念，因为在这个主题上有许多可以尝试的例外。</p><p id="b56f" class="pw-post-body-paragraph ll lm it lo b lp lq kd lr ls lt kg lu mi lw lx ly mj ma mb mc mk me mf mg mh im bi translated">我希望你喜欢这篇文章。通过我的<a class="ae lh" href="https://www.linkedin.com/in/data-scientist-95040a1ab/" rel="noopener ugc nofollow" target="_blank"> LinkedIn </a>和<a class="ae lh" href="https://twitter.com/amitprius" rel="noopener ugc nofollow" target="_blank"> twitter </a>联系我。</p><h1 id="d5ec" class="pb mr it bd mx pc pd pe na pf pg ph nd ki pi kj ng kl pj km nj ko pk kp nm pl bi translated">推荐文章</h1><p id="65b2" class="pw-post-body-paragraph ll lm it lo b lp nn kd lr ls no kg lu mi np lx ly mj nq mb mc mk nr mf mg mh im bi translated">1.<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/8-active-learning-insights-of-python-collection-module-6c9e0cc16f6b?source=friends_link&amp;sk=4a5c9f9ad552005636ae720a658281b1">8 Python的主动学习见解收集模块</a> <br/> 2。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/numpy-linear-algebra-on-images-ed3180978cdb?source=friends_link&amp;sk=d9afa4a1206971f9b1f64862f6291ac0"> NumPy:图像上的线性代数</a>T5】3。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/exception-handling-concepts-in-python-4d5116decac3?source=friends_link&amp;sk=a0ed49d9fdeaa67925eac34ecb55ea30">Python中的异常处理概念</a> <br/> 4。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/pandas-dealing-with-categorical-data-7547305582ff?source=friends_link&amp;sk=11c6809f6623dd4f6dd74d43727297cf">熊猫:处理分类数据</a> <br/> 5。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/hyper-parameters-randomseachcv-and-gridsearchcv-in-machine-learning-b7d091cf56f4?source=friends_link&amp;sk=cab337083fb09601114a6e466ec59689">超参数:机器学习中的RandomSeachCV和GridSearchCV</a><br/>6。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/fully-explained-linear-regression-with-python-fe2b313f32f3?source=friends_link&amp;sk=53c91a2a51347ec2d93f8222c0e06402" rel="noopener">用Python </a> <br/> 7全面讲解了线性回归。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/fully-explained-logistic-regression-with-python-f4a16413ddcd?source=friends_link&amp;sk=528181f15a44e48ea38fdd9579241a78" rel="noopener">用Python </a> <br/>充分解释了Logistic回归8。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/data-distribution-using-numpy-with-python-3b64aae6f9d6?source=friends_link&amp;sk=809e75802cbd25ddceb5f0f6496c9803">数据分发使用Numpy与Python </a> <br/> 9。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/decision-trees-vs-random-forests-in-machine-learning-be56c093b0f?source=friends_link&amp;sk=91377248a43b62fe7aeb89a69e590860">机器学习中的决策树vs随机森林</a> <br/> 10。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/standardization-in-data-preprocessing-with-python-96ae89d2f658?source=friends_link&amp;sk=f348435582e8fbb47407e9b359787e41">用Python实现数据预处理的标准化</a></p></div></div>    
</body>
</html>